name: CI Pipeline

# Ejecuta el workflow en los eventos "push" o "pull request" en la rama main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Nombre del job principal
  build-and-test:
    # Selecciona el sistema operativo en el que se ejecutará el job
    runs-on: ubuntu-latest

    steps:
      # Verificar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura Node.js (reemplaza por otra configuración si tu proyecto no usa Node)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # Ejecutar los tests del proyecto (esto puede variar según el gestor de test que uses)
      - name: Run tests
        run: npm run dev

      # Ejecutar un análisis de estilo y código, en este caso usando ESLint
      - name: Run linter
        run: npm run lint
